export const CREATE_REQUEST = 'CREATE_REQUEST';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';

export const GET_CARRIERS = 'GET_CARRIERS';
export const GET_CARRIERS_REQUEST = 'GET_CARRIERS_REQUEST';
export const GET_CARRIERS_SUCCESS = 'GET_CARRIERS_SUCCESS';
export const GET_CARRIERS_FAILURE = 'GET_CARRIERS_FAILURE';
export const DESTROY_TOPIC = 'DESTROY_TOPIC';
export const TYPING = 'TYPING';
